FROM ruby:3.3.6-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs npm postgresql-client && \
    npm install -g yarn && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . /rails
RUN chmod +x bin/*

EXPOSE 3000
CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]
